### ISSUE TITLE
Exception during drawing

### ISSUE THREAD

**Issue by neumantm** [FIUS/ICGE2#117]
```
Exception in thread "STM-TickTimer" java.lang.NullPointerException
	at java.desktop/javax.swing.BufferStrategyPaintManager.flushAccumulatedRegion(BufferStrategyPaintManager.java:369)
	at java.desktop/javax.swing.BufferStrategyPaintManager.endPaint(BufferStrategyPaintManager.java:333)
	at java.desktop/javax.swing.RepaintManager.endPaint(RepaintManager.java:1414)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5209)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5025)
	at de.unistuttgart.informatik.fius.icge.ui@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.ui.internal.SwingPlayfieldDrawer.draw(SwingPlayfieldDrawer.java:232)
	at de.unistuttgart.informatik.fius.icge.ui@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.ui.internal.SwingPlayfieldDrawer.setDrawables(SwingPlayfieldDrawer.java:218)
	at de.unistuttgart.informatik.fius.icge.ui@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.ui.internal.SwingPlayfieldDrawer$1.setDrawables(SwingPlayfieldDrawer.java:120)
	at de.unistuttgart.informatik.fius.icge.simulation@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.simulation.internal.playfield.StandardPlayfield.drawEntities(StandardPlayfield.java:115)
	at de.unistuttgart.informatik.fius.icge.simulation@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.simulation.internal.playfield.StandardPlayfield.lambda$initialize$0(StandardPlayfield.java:65)
	at de.unistuttgart.informatik.fius.icge.simulation@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.simulation.internal.StandardSimulationClock.tickSimulation(StandardSimulationClock.java:259)
	at de.unistuttgart.informatik.fius.icge.simulation@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.simulation.internal.StandardSimulationClock.tick(StandardSimulationClock.java:231)
	at de.unistuttgart.informatik.fius.icge.simulation@2.2.3-Snapshot/de.unistuttgart.informatik.fius.icge.simulation.internal.StandardSimulationClock$1.run(StandardSimulationClock.java:127)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

Occurred on 938564a2a9135723ee00b6b2767016926539ec5b

**Comment by neumantm** [comment]
First stack frame in our code: https://github.com/FIUS/ICGE2/blob/938564a2a9135723ee00b6b2767016926539ec5b/ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingPlayfieldDrawer.java#L232

**Comment by neumantm** [comment]
Next NPE i found: 
```
Exception in thread "STM-TickTimer" java.lang.NullPointerException
	at java.desktop/javax.swing.BufferStrategyPaintManager.flushAccumulatedRegion(BufferStrategyPaintManager.java:373)
	at java.desktop/javax.swing.BufferStrategyPaintManager.endPaint(BufferStrategyPaintManager.java:333)
	at java.desktop/javax.swing.RepaintManager.endPaint(RepaintManager.java:1414)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5209)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5025)
	at de.unistuttgart.informatik.fius.icge.ui/de.unistuttgart.informatik.fius.icge.ui.internal.SwingPlayfieldDrawer.draw(SwingPlayfieldDrawer.java:235)
	at de.unistuttgart.informatik.fius.icge.ui/de.unistuttgart.informatik.fius.icge.ui.internal.SwingPlayfieldDrawer.setDrawables(SwingPlayfieldDrawer.java:218)
	at de.unistuttgart.informatik.fius.icge.ui/de.unistuttgart.informatik.fius.icge.ui.internal.SwingPlayfieldDrawer$1.setDrawables(SwingPlayfieldDrawer.java:120)
	at de.unistuttgart.informatik.fius.icge.simulation/de.unistuttgart.informatik.fius.icge.simulation.internal.playfield.StandardPlayfield.drawEntities(StandardPlayfield.java:115)
	at de.unistuttgart.informatik.fius.icge.simulation/de.unistuttgart.informatik.fius.icge.simulation.internal.playfield.StandardPlayfield.lambda$0(StandardPlayfield.java:65)
	at de.unistuttgart.informatik.fius.icge.simulation/de.unistuttgart.informatik.fius.icge.simulation.internal.StandardSimulationClock.tickSimulation(StandardSimulationClock.java:259)
	at de.unistuttgart.informatik.fius.icge.simulation/de.unistuttgart.informatik.fius.icge.simulation.internal.StandardSimulationClock.tick(StandardSimulationClock.java:231)
	at de.unistuttgart.informatik.fius.icge.simulation/de.unistuttgart.informatik.fius.icge.simulation.internal.StandardSimulationClock$1.run(StandardSimulationClock.java:127)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

this happened on e686e7709dfa3faa7b26e004c461ad82c2ff016d

**Comment by neumantm** [comment]
Seems to have been fixed by #121
